apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-web
spec:
  ports:
  - port: {{ .Values.app.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.app.containerPort }}
  selector:
    app: {{ .Chart.Name }}-web
  type: ClusterIP
